import Foundation

typealias ErrorHandler = (_ message: String, _ type: ErrorType) -> Void

public enum ErrorType {
    // Generated by a "TODO" note in the ink source
    case author
    
    // You should probably fix this, but it's not critical
    case warning
    
    // Critical error that can't be recovered from
    case error
}
